default_session = "~"
display_full_path = true
bookmarks = [
    "~",
    "~/notes",
    "~/dev/git.lyon.labo.int/sds/cloud-security/apps/cse",
    "~/dev/git.lyon.labo.int/sds/cloud-security/apps/ecdn",
    "~/dev/git.lyon.labo.int/sds/cloud-security/apps/orchestrator",
]

[[search_dirs]]
path = "~/dev"
depth = 10

[[search_dirs]]
path = "~/.dotfiles"
depth = 1

